{
 "title": "Weka Cluster Overview",
 "tags": [ "#weka" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "weka_datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Select Cluster" }
  ]
 },
 "panels": [
  { "title": "Cluster Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "weka_info", "legendFormat": "{{cluster}}" }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weka_info", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weka_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "License Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weka_info", "legendFormat": "{{license_status}}" }
   ]
  },
  {
   "title": "Link Layer",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weka_info", "legendFormat": "{{link_layer}}" }
   ]
  },
  {
   "title": "IO Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weka_info", "legendFormat": "{{io_status}}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weka_uptime", "legendFormat": "{{cluster}}" }
   ]
  },
  {
   "title": "Total Capacity",
   "type": "stat",
   "description": "Total capacity of the cluster",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weka_drive_storage_total_bytes" }
   ]
  },
  {
   "title": "Unprovisioned",
   "type": "stat",
   "description": "Capacity that has not been put into a filesystem",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weka_drive_storage_unprovisioned_bytes"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(weka_alerts)" }
   ]
  },
  {
   "title": "Current Throughput",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weka_overview_activity_write_bytespersec+weka_overview_activity_read_bytespersec",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Avg Throughput",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (weka_overview_activity_write_bytespersec+weka_overview_activity_read_bytespersec)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Cluster Used Capacity",
   "type": "graph",
   "description": "Total Used drive capacity",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "weka_drive_storage_total_bytes - weka_drive_storage_unprovisioned_bytes",
     "legendFormat": "{{cluster}} - allocated"
    },
    { "expr": "weka_drive_storage_total_bytes", "legendFormat": "{{cluster}} - total" }
   ]
  },
  {
   "title": "Protection Status",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weka_protection", "legendFormat": "{{numFailures}} Failures" }
   ]
  },
  { "title": "Cluster Filesystem Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "FS Capacity Utilization %",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "weka_fs_utilization_percent", "legendFormat": "{{fsname}}" }
   ]
  },
  {
   "title": "FS Total Used Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "weka_fs_used_bytes", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "FS Total Used Capacity % Prediction next 30 days based on prev 30 days",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "abs(predict_linear(weka_fs_utilization_percent[30d], 86400*30)) < 100",
     "legendFormat": "{{fsname}}"
    }
   ]
  },
  {
   "title": "FS Capacity Utilization %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "weka_fs_utilization_percent", "legendFormat": "{{fsname}}" }
   ]
  },
  {
   "title": "Cluster CPU Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Weka FE Core Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg by (host_name) (weka_stats{stat=\"CPU_UTILIZATION\",node_role=\"FRONTEND\"})",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Weka Compute Core Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg by (host_name) (weka_stats{stat=\"CPU_UTILIZATION\",node_role=\"COMPUTE\"})",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Weka Drives Core Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg by (host_name) (weka_stats{stat=\"CPU_UTILIZATION\",node_role=\"DRIVES\"})",
       "legendFormat": "{{host_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster-wide IO Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operations per second, total",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      { "expr": "weka_overview_activity_ops", "legendFormat": "{{cluster}}" }
     ]
    },
    {
     "title": "Throughput per second, total",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 9, "y": 30 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "weka_overview_activity_read_bytespersec + weka_overview_activity_write_bytespersec",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Read vs Write IOPS, total",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "weka_overview_activity_write_iops",
       "legendFormat": "writes"
      },
      {
       "expr": "weka_overview_activity_read_iops",
       "legendFormat": "reads"
      }
     ]
    },
    {
     "title": "Read vs Write Bytes per second, total",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 9, "y": 36 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "weka_overview_activity_read_bytespersec",
       "legendFormat": "reads"
      },
      {
       "expr": "weka_overview_activity_write_bytespersec",
       "legendFormat": "writes"
      }
     ]
    },
    {
     "title": "Metadata, total",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "weka_overview_activity_ops - weka_overview_activity_write_iops - weka_overview_activity_read_iops",
       "legendFormat": "metadata ops"
      }
     ]
    },
    {
     "title": "Download vs Upload Object Store Data Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 9, "y": 42 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "weka_overview_activity_object_download_bytespersec",
       "legendFormat": "download"
      },
      {
       "expr": "weka_overview_activity_object_upload_bytespersec",
       "legendFormat": "upload"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster IO Statistcs by Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operations per second by host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum by (host_name) (weka_stats{category=\"ops\",stat=\"OPS\"})",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Total Throughput per second by host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 31 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (host_name) (weka_stats{category=\"ops\",stat=\"THROUGHPUT\"})",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Reads per second by host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum by (host_name) (weka_stats{category=\"ops\",stat=\"READS\"})",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Read Bytes per second by host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 38 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (host_name) (weka_stats{category=\"ops\",stat=\"READ_BYTES\"})",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Writes per second by host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum by (host_name) (weka_stats{category=\"ops\",stat=\"WRITES\"})",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Write Bytes per second by host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 45 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (host_name) (weka_stats{category=\"ops\",stat=\"WRITE_BYTES\"})",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Metadata ops by host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (host_name) ( weka_stats{category=\"ops\",stat=\"OPS\"} ) - sum by (host_name)( weka_stats{category=\"ops\",stat=\"READS\"} )- sum by (host_name)( weka_stats{category=\"ops\",stat=\"WRITES\"} )",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Total IO Latency by host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 52 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "avg by (host_name) (weka_stats{category=\"ops\",stat=\"READ_LATENCY\"})",
       "legendFormat": "{{host_name}} read"
      },
      {
       "expr": "avg by (host_name) (weka_stats{category=\"ops\",stat=\"WRITE_LATENCY\"})",
       "legendFormat": "{{host_name}} write"
      }
     ]
    }
   ]
  },
  {
   "title": "Top Clients",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Clients by IOPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "topk( 5, sum by (host_name) (weka_stats{category=\"ops\",stat=\"READS\",host_role=\"client\"}) + sum by (host_name) (weka_stats{category=\"ops\",stat=\"WRITES\",host_role=\"client\"}))  ",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Clients by Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 32 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "topk( 5, sum by (host_name) (weka_stats{category=\"ops\",stat=\"THROUGHPUT\",host_role=\"client\"}))",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Clients by read iops",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "topk( 5, sum by (host_name) (weka_stats{category=\"ops\",stat=\"READS\",host_role=\"client\"}))",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Clients by read bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 39 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "topk( 5, sum by (host_name) (weka_stats{category=\"ops\",stat=\"READ_BYTES\",host_role=\"client\"}))",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Clients by write iops",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "topk( 5, sum by (host_name) (weka_stats{category=\"ops\",stat=\"WRITES\",host_role=\"client\"}))",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Clients by write bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 46 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "topk( 5, sum by (host_name) (weka_stats{category=\"ops\",stat=\"WRITE_BYTES\",host_role=\"client\"}))",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Clients by Read Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "topk( 5, sum by (host_name) (weka_stats{category=\"ops\",stat=\"READ_LATENCY\",host_role=\"client\"}))",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Clients by Write Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 53 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "topk( 5, sum by (host_name) (weka_stats{category=\"ops\",stat=\"WRITE_LATENCY\",host_role=\"client\"}))",
       "legendFormat": "{{host_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Clients by Metadata Ops",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk( 5, sum by (host_name) (weka_stats{category=\"ops\",stat=\"OPS\",host_role=\"client\"}) - sum by (host_name) (weka_stats{category=\"ops\",stat=\"READS\",host_role=\"client\"}) - sum by (host_name) (weka_stats{category=\"ops\",stat=\"WRITES\",host_role=\"client\"}))",
       "legendFormat": "{{host_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "per core stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization by NodeId/Core",
     "type": "graph",
     "gridPos": { "h": 14, "w": 22, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "weka_stats{category=\"cpu\",stat=\"CPU_UTILIZATION\"}",
       "legendFormat": "{{node_id}} {{host_name}} {{node_role}}"
      }
     ]
    }
   ]
  }
 ]
}