{
 "title": "S3 Object Storage",
 "description": "S3 dashboard",
 "tags": [
  "object-storage",
  "prometheus",
  "weka"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(minio_version_info,instance)"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Stats",
   "type": "graph",
   "description": "S3 server instances memory usages",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "resident {{instance}}"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "virtual {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Stats",
   "type": "graph",
   "description": "Total user and system CPU time spent in percentage by S3 server instances",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Data Transmitted",
   "type": "graph",
   "description": "Data sent/received by current S3 server instances",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(s3_tx_bytes_total{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "Sent {{instance}}"
    },
    {
     "expr": "sum(rate(s3_rx_bytes_total{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "Received {{instance}}"
    }
   ]
  },
  {
   "title": "Internode Data Transmitted",
   "type": "graph",
   "description": "Internode data sent/received by current S3 server instances",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(internode_tx_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Sent {{instance}}"
    },
    {
     "expr": "rate(internode_rx_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Received {{instance}}"
    }
   ]
  },
  {
   "title": "S3 Total Requests/Min",
   "type": "graph",
   "description": "Total number of S3 requests in current server instances",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(s3_requests_total{instance=~\"$instance\"}[1m])) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "S3 Active Requests",
   "type": "graph",
   "description": "Total number of active S3 requests in current S3 server instances",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "rate(s3_requests_current{instance=~\"$instance\"}[$interval])  ",
     "legendFormat": "{{instance}} {{api}}"
    }
   ]
  },
  {
   "title": "Total S3 Request Errors",
   "type": "graph",
   "description": "Total number of errors in s3 requests in current S3 server instances",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(s3_errors_total{instance=~\"$instance\"}) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "S3 Requests Latency",
   "type": "heatmap",
   "description": "Latency information of the requests on S3 server instances",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "irate(s3_ttfb_seconds_bucket{instance=~\"$instance\",api=\"getobject\"}[5m])"
    }
   ]
  },
  {
   "title": "HTTP Request Status",
   "type": "graph",
   "description": "HTTP request status of S3 server response",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{code=\"200\"}"
    }
   ]
  },
  {
   "title": "S3 Requests Latency",
   "type": "graph",
   "description": "Latency information of the requests on S3 server instances",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(s3_ttfb_seconds_sum{instance=~\"$instance\"}[$__range])",
     "legendFormat": "{{instance}} {{api}}"
    }
   ]
  },
  {
   "title": "S3 Req / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "targets": [
    { "expr": "sum(s3_requests_current)", "legendFormat": "s3 Req / Sec" }
   ]
  }
 ]
}