{
 "title": "Weka Metrics Exporter Stats",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "weka_datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Resident memory bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Elapsed time to collect all stats",
   "type": "graph",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "weka_metrics_exporter_weka_metrics_gather_seconds",
     "legendFormat": "{{}}"
    }
   ]
  },
  {
   "title": "Elapsed time to collect individual stats",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "weka_metrics_exporter_cmd_execute_seconds",
     "legendFormat": "{{stat}}"
    }
   ]
  }
 ]
}