{
 "title": "(experimental) Weka Realtime Stats",
 "description": "Weka Server/Client Details",
 "tags": [ "#weka" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "weka_datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(weka_info,cluster)"
    }
   },
   {
    "name": "host_name",
    "query": {
     "query": "label_values(weka_stats{cluster=\"$cluster\"},host_name)"
    }
   },
   { "name": "adhoc" }
  ]
 },
 "panels": [
  {
   "title": "Top 5 by iops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, weka_rtstats{cluster=\"$cluster\",host_name=~\".+\",stat=\"ops_per_second\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Top 5 by read throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "topk(5, weka_rtstats{cluster=\"$cluster\",host_name=~\".+\",stat=\"read_bytes_per_second\"})",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "options": {
    "content": "<img src=/public/img/weka/WekaColor.svg>"
   }
  },
  { "title": "Client Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "$host_name  - Total Client OPS",
   "type": "graph",
   "description": "Total Operations (io and metadata)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum (weka_rtstats{cluster=\"$cluster\",host_name=~\"$host_name\",stat=\"ops_per_second\"})",
     "legendFormat": "Operations per sec"
    }
   ]
  },
  {
   "title": "$host_name - Total Client Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (weka_rtstats{cluster=\"$cluster\",host_name=~\"$host_name\",stat=\"read_bytes_per_second\"} + weka_rtstats{cluster=\"$cluster\",host_name=~\"$host_name\",stat=\"read_bytes_per_second\"})",
     "legendFormat": "throughput"
    }
   ]
  },
  {
   "title": "$host_name - OPS Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum (weka_rtstats{cluster=\"$cluster\",host_name=~\"$host_name\",stat=\"reads_per_second\"})",
     "legendFormat": "reads"
    },
    {
     "expr": "sum (weka_rtstats{cluster=\"$cluster\",host_name=~\"$host_name\",stat=\"writes_per_second\"})",
     "legendFormat": "writes"
    },
    {
     "expr": "sum (weka_rtstats{cluster=\"$cluster\",host_name=~\"$host_name\",stat=\"ops_per_second\"}) - sum (weka_rtstats{cluster=\"$cluster\",host_name=~\"$host_name\",stat=\"reads_per_second\"}) - sum(weka_rtstats{cluster=\"$cluster\",host_name=~\"$host_name\",stat=\"writes_per_second\"})",
     "legendFormat": "metadata ops"
    }
   ]
  },
  {
   "title": "$host_name - Throughput Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (weka_rtstats{cluster=\"$cluster\",host_name=~\"$host_name\",stat=\"read_bytes_per_second\"})",
     "legendFormat": "read bytes"
    },
    {
     "expr": "sum (weka_rtstats{cluster=\"$cluster\",host_name=~\"$host_name\",stat=\"write_bytes_per_second\"})",
     "legendFormat": "write bytes"
    }
   ]
  },
  {
   "title": "$host_name - Average Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg (weka_rtstats{cluster=\"$cluster\",host_name=~\"$host_name\",stat=\"read_latency_usecs\"})",
     "legendFormat": "read latency"
    },
    {
     "expr": "avg (weka_rtstats{cluster=\"$cluster\",host_name=~\"$host_name\",stat=\"write_latency_usecs\"})",
     "legendFormat": "write latency"
    }
   ]
  },
  {
   "title": "$host_name - CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg (weka_rtstats{cluster=\"$cluster\",host_name=~\"$host_name\",stat=\"cpu_utilization_percentage\"})",
     "legendFormat": "% CPU"
    }
   ]
  },
  {
   "title": "$host_name - Network Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (weka_rtstats{cluster=\"$cluster\",host_name=~\"$host_name\",stat=\"L6RX_bytes_per_second\"})",
     "legendFormat": "receive bytes"
    },
    {
     "expr": "sum (weka_rtstats{cluster=\"$cluster\",host_name=~\"$host_name\",stat=\"L6TX_bytes_per_second\"})",
     "legendFormat": "transmit bytes"
    }
   ]
  },
  { "title": "Per Node Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Read Ops Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "weka_rtstats{cluster=\"$cluster\",host_name=~\"$host_name\",stat=\"reads_per_second\"}",
     "legendFormat": "{{node_id}} reads"
    }
   ]
  },
  {
   "title": "Write OPS Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "weka_rtstats{cluster=\"$cluster\",host_name=~\"$host_name\",stat=\"writes_per_second\"}",
     "legendFormat": "{{node_id}} writes"
    }
   ]
  },
  {
   "title": "Read Throughput Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "weka_rtstats{cluster=\"$cluster\",host_name=~\"$host_name\",stat=\"read_bytes_per_second\"}",
     "legendFormat": "{{node_id}} reads"
    }
   ]
  },
  {
   "title": "Write Throughput Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "weka_rtstats{cluster=\"$cluster\",host_name=~\"$host_name\",stat=\"write_bytes_per_second\"}",
     "legendFormat": "{{node_id}} writes"
    }
   ]
  },
  {
   "title": "Read Latency Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "weka_rtstats{cluster=\"$cluster\",host_name=~\"$host_name\",stat=\"read_latency_usecs\"}",
     "legendFormat": "{{node_id}} reads"
    }
   ]
  },
  {
   "title": "Write Latency Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "weka_rtstats{cluster=\"$cluster\",host_name=~\"$host_name\",stat=\"write_latency_usecs\"}",
     "legendFormat": "{{node_id}} writes"
    }
   ]
  },
  {
   "title": "Cpu Utilization Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "weka_rtstats{cluster=\"$cluster\",host_name=~\"$host_name\",stat=\"cpu_utilization_percentage\"}",
     "legendFormat": "{{node_id}} {{node_role}}"
    }
   ]
  }
 ]
}